### PR TITLE
Added level progression to level select scene and new export for web server.

### LINKED ISSUE #123: Registration page needs register functionality
## Describe the issue

The registration page currently does not create a new user when credentials are provided.

## To Reproduce

Start frontend and backend.
Navigate to /registration.
Try to create a user.

## Expected behavior

A new user is created if a user does not exist already.

## Possible Solution

Update page to utilize users API. Update the users API to check for duplicate users.

### PR DESCRIPTION
**Pull request by MoldyPotat**
## Overview
Please provide a brief overview of what this pull request aims to achieve. For instance, you might be fixing a bug, adding a new feature, or updating documentation. 
This addition is meant to add level progression to the game. It will lock future levels in map select until it is reported that the user has beaten the previous level. 

## Related Issue(s)
List any related issues this pull request addresses, using a keyword to automatically close issues when the pull request is merged (e.g., "closes #123").
progress #80 still need to implement updating level dictionary when level is completed.

## Changes
Describe in detail the changes made in this pull request. Include specifics about modifications to files, added or removed functionalities, and any other changes that contributors and reviewers should be aware of.
Changed level script files to implement progression locking.
Made new export of current version of game to try and host on web server.

### Added
- List any new files, features, or functionalities added.
Added level progression to the level scene.

### Changed
- Detail any modifications to existing files, features, or functionalities.
Modified player inventory scrip to format the level names and make sure level one is enabled.
Modified Level2.gd level3.gd to allow for the level lock system.
Re exported the game for web server so many auto generated files changes.

### Removed
- List any files, features, or functionalities that have been removed.
N/A

### Fixed
- Describe any bugs that have been fixed.
N/A

## Screenshots
If applicable, add screenshots to help explain your changes visually. This is particularly useful for UI-related changes.
image

## Instructions for Testing
Provide detailed instructions on how reviewers can test the changes. Include steps to follow, any relevant URLs, user credentials if needed, and expected outcomes.

## Checklist before Merging
- [X] I have performed a self-review of my own code.
- [X] I have added tests that prove my fix is effective or that my feature works.
- [X] I have added necessary documentation (if appropriate).
- [X] I have ensured the changes adhere to the project's coding standards and guidelines.

## Additional Comments
Include any additional comments or context that you think might be helpful for the reviewers.

### CODE REVIEW

**Comment by thegreatzoidberg** [comment]
### Pull Request Review:

- **Readability**:
  - Code is readable with comments.

- **Code Quality**:
  - I don't see any bugs here.

- **Testing**:
  - No new test files, but still need to figure out how to track on Godot.

- **Functionality**:
  - Levels now need to be beaten sequentially.

- **Housekeeping**:
  - No junk files added, don't see any AI mentioned.

### Additional Comments:
  - I would keep level1 initialized as 0 instead of 1.  We could use it to track total completion amount and just never lock level 1.

**Review by thegreatzoidberg — APPROVED** [review]

**Comment by MoldyPotat** [comment]
@thegreatzoidberg Thats a good point for the level tracking will send in that change.

**Review by Ruben14789 — APPROVED** [review]
Pull Request Review:

    Readability:
        Code logic is easy to follow and does what is described 

    Code Quality:
       Code is easy to understand with the comments made

    Testing:
        Progress of locked levels are shown 

    Functionality:
        Added level progression a nice feature to have 

    Housekeeping:
        No AI mentioned.

**Review by Alexmc567 — APPROVED** [review]
Readability: Code has great readability. A lot of comments explaining the code.
Code Quality: Code looks to be of high quality and does what it is intended to do.
Testing: No additional tests added.
Functionality: Code appears to work as intended. 
Housekeeping: No bad files, no AI mentioned, & good overall comments.

**Pull request merged**
