### PR TITLE
Added quiz page

### PR DESCRIPTION
**Pull request by Alexmc567**
## Overview
Added basic functionality for quiz page

## Related Issue(s)
Missing quiz page - This should be closed after this is merged

## Changes
Added basic functionality to the quiz page. 

### Added
Added QuizPage.js
Added QuizPage.module.css

## Screenshots
Capture

The full quiz should now be completable. Clicking on an answer will change it to green to signify your choice. Clicking next will unselect your option and display the next question.

## Instructions for Testing
Clone the repo
Go to app
npm install
npm start
navigate to http://localhost:3000/quiz

## Checklist before Merging
- [x] I have performed a self-review of my own code.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary documentation (if appropriate).
- [x] I have ensured the changes adhere to the project's coding standards and guidelines.

## Additional Comments
Current issues:
Scores do not add up correctly
Additionally, I hard coded the total possible points temporarily, as I just wanted to get the quiz page up as soon as possible if other people want to work on it.

### CODE REVIEW

**Comment by Alexmc567** [comment]
I just noticed the other pull request before this one - Since we both modified App.js will I need to reupload my pull request after the other one is merged? (New to github, not sure if thats how that works)

**Comment by dusek2** [comment]
## Pull Request Review checklist

- **Readability**:
    - Read the PR description. Does it align with the proposed changes?
    - Check if the code is clear and the logic is easy to follow.

Answer:  Code readable and logic

- **Code Quality**:
    - Are there comments explaining complex sections of code?
    - Is the programming style consistent with the project's standards?

Answer: Consistent code and comments included

- **Testing**:
    - Is Test coverage still >90%
    - Did code pass Github Actions CI system's pass all tests?

Answer: Test coverage still not 90% we need to work on it this week.

- **Functionality**:
    - Are all changes backward compatible?
    - Does the PR resolve an existing issue?

Answer: yes

- **Housekeeping**:
    - Are all files committed free from unnecessary (e.g., logs, 
      temporary files)?
    - Has any assistance from Generative AI been linked to PR or commented 
      below?

Answer:files cleared, no assistance

### Additional Comments:

Answer:

**Review by dusek2 — APPROVED** [review]

**Comment by barkangel** [comment]
I fixed the merge conflict, added your 2 new quiz lines to App.js as well as my 2 quest page lines to App.js

**Review by barkangel — APPROVED** [review]
## Pull Request Review checklist

- Readability:
	- Pull Request description matches proposed changes. Code is easy to understand and the logic is easy to follow

- Code Quality:
	- Comments explain the sections of code, complex and simple. Programming style is consistent with the Javascript standards of the program.

- Testing:
	- Test coverage is not high, but that is OK for now. Github Actions CI system passed all tests.

- Functionality:
	- Yes, changes backward compatible. PR resolves existing issue #32 which is good to close.

- Housekeeping:
	- Files are free from unnecessary temporary files and logs and other framework generated files. AI is not linked, thus assumed not used.

- Additional Comments:
	- Good screenshot of quiz page. I suggest a different font for future use.
	- PR good to merge!

**Pull request merged**
