### PR TITLE
Added Dependency Caching and Comments to workflow.yml

### PR DESCRIPTION
**Pull request by thegreatzoidberg**
## Overview
Added Dependency Caching to workflow.yml to avoid downloading them multiple times.
Added Comment Headers to workflow.yml for easier reading.

### Added
- Dependency Caching and Check for Cache Hit before installing dependencies
- Comment Headers for each section of the file

## Checklist before Merging
- [x] I have performed a self-review of my own code.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary documentation (if appropriate).
- [x] I have ensured the changes adhere to the project's coding standards and guidelines.

### CODE REVIEW

**Review by MoldyPotat — APPROVED** [review]
The implementation looks good just curious what the cache accomplishes.

**Comment by thegreatzoidberg** [comment]
All it does is speed up the workflow file by storing the dependencies instead of downloading them again each time it runs.

**Review by dusek2 — APPROVED** [review]
That makes sense! Thank you, no need to redownload all of the dependencies!

**Comment by dusek2** [comment]
Im not sure how to resolve the conflict, we can do it at the meeting tonight?

**Comment by thegreatzoidberg** [comment]
I'll look at the conflict.

**Comment by thegreatzoidberg** [comment]
Gonna fix the 50 commits and the conflict really quick.

**Pull request closed without merging**
