### PR TITLE
Adding CodeCov code coverage upload for enhanced test coverage reports

### PR DESCRIPTION
**Pull request by dusek2**
## Overview
This pull request integrates Codecov with our GitHub Actions workflow to enhance code coverage reporting. The addition allows us to upload coverage reports automatically, helping improve visibility into the quality and robustness of our codebase.

## Related Issue(s)
This implementation doesn't specifically address any open issues but provides a foundation for more rigorous testing frameworks in future updates.

## Changes
This pull request modifies the GitHub Actions workflow file to include steps for uploading code coverage reports to Codecov. This integration is intended to streamline our CI/CD pipeline by automating coverage report generation and submission.

### Added
- Code for downloading, setting permissions, and executing the Codecov uploader script within the CI workflow.

### Changed
- `.github/workflows/workflow.yml`:
  - Added steps in the CI job to run Codecov after test coverage is generated.

### Removed
- No files or functionalities were removed in this pull request.

### Fixed
- This pull request does not include bug fixes.

## Screenshots
Not applicable, as the changes do not affect the UI.

## Instructions for Testing
To test this implementation:
1. Trigger any push or pull request event that runs the modified workflow.
2. Verify that the GitHub Actions workflow completes successfully.
3. Check the output of the CI run to ensure the Codecov step executes correctly.
4. Visit our Codecov dashboard to see the newly uploaded coverage report.
5. Ensure the report accurately reflects the code coverage of the latest commit.

## Checklist before Merging
- [x] I have performed a self-review of my own code.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary documentation (if appropriate).
- [x] I have ensured the changes adhere to the project's coding standards and guidelines.

## Additional Comments
Future updates may include further enhancements to the test scripts themselves to improve coverage metrics. Reviewers should ensure that the Codecov token used is secure and that it does not leak in logs or outputs.

### CODE REVIEW

**Comment by dusek2** [comment]
image

for app side

**Review by Ruben14789 — APPROVED** [review]
Pull Request Review:

    Readability:
    Changes documented well on pull request 

    Code Quality:
    Adds coverage from Codecov

    Testing:
    Addition of screenshot in the comment shows what the addition adds to it 

    Functionality:
    Enhances coverage report

    Housekeeping:
    No AI usage mentioned 

Additional Comments:
Nice addition to help illustrate our code coverage better!

**Comment by FernFinder** [comment]
### Pull Request Review:

- **Readability**: Compact workflow code change that is readable and appropriately named.

- **Code Quality**: Secrets are utilized to enhance repository security/

- **Testing**: Visualized coverage reports will enhance testing and make it easier to create a report.

- **Housekeeping**: No AI documentation needed.

### Additional Comments:
Cool addition!

**Review by FernFinder — APPROVED** [review]
### Pull Request Review:

- **Readability**: Compact workflow code change that is readable and appropriately named.

- **Code Quality**: Secrets are utilized to enhance repository security/

- **Testing**: Visualized coverage reports will enhance testing and make it easier to create a report.

- **Housekeeping**: No AI documentation needed.

### Additional Comments:
Cool addition!

**Review by barkangel — APPROVED** [review]
### Pull Request Review:

- **Readability**:
 Code's purpose is well understood in workflow.yml

- **Code Quality**:
Code is straight to the point, only a few lines.

- **Testing**:
CodeCov testing added, very well received addition!

- **Functionality**:
CodeCov adding more code coverage methods for out project, very good

- **Housekeeping**:
No AI noted, good to go!

### Additional Comments:
Good to merge!

**Pull request merged**
