### PR TITLE
Added visual uniformity to game homepage and return to menue button on level select.

### PR DESCRIPTION
**Pull request by MoldyPotat**
## Overview 
Changed the visual look of the main menu to closer resemble rest of website design. Added home button to level select. Imported robot font and other images for homepage.

## Changes
Added website logo and background to the game home page in order to bring it to a visual similarity to the rest of the app.
Edited the audio options to include a style box to allow for legibility of text and slider over new background.
Uploaded Roboto Font.
Edited Level select to include a new button that leads back to game home. 

### Added
- List any new files, features, or functionalities added.
- Added marble background to main
- Added LifeQuest logo to main
- Added return home button to level select.

### Changed
- Changed audio setting to be encased in a panned to allow for background color around options.

## Screenshots
image
image

## Instructions for Testing
-Run godot see if logo and background appear. Check if return to menu button works by choosing no then yes option.

## Checklist before Merging
- [X] I have performed a self-review of my own code.
- [X] I have added tests that prove my fix is effective or that my feature works.
- [X] I have added necessary documentation (if appropriate).
- [X] I have ensured the changes adhere to the project's coding standards and guidelines.

### CODE REVIEW

**Review by dusek2 — APPROVED** [review]
### Pull Request Review:

- **Readability**:
  Good; clear description, well-documented changes.

- **Code Quality**:
  Consistent with existing codebase, improvements noted.

- **Testing**:
  Instructions provided; manual test needed.

- **Functionality**:
  Enhances usability; integrates home button, visual changes.

- **Housekeeping**:
  Meets contribution guidelines, ready for merging.

### Additional Comments:
  Ensure all functionalities are tested on different devices.
  
  
  Thank you this looks great!!

**Review by Alexmc567 — APPROVED** [review]
Readability: Code is well documented and easy to understand.
Code Quality: Code appears to be of high quality.
Testing: Testing instructions clearly provided.
Functionality: Code appears to properly work as intended in adding uniformity & return to menu.
Housekeeping: No junk files added. No use of AI mentioned. Looks good!

**Review by barkangel — APPROVED** [review]
### Pull Request Review:

- **Readability**:
 Code is easily readable and viewable

- **Code Quality**:
Code is quality and changes made were well recieved, especially the main scene with the home changes and logo!

- **Testing**:
Manual testing is required within game, so testing is OK!

- **Functionality**:
Home button added and code increases overall functionality of the game

- **Housekeeping**:
No AI noted, good to go!

### Additional Comments:
Love the home button, good to merge!

**Comment by thegreatzoidberg** [comment]
### Pull Request Review:

- **Readability**:
  - Code is readable, with comments.

- **Code Quality**:
  -  Code looks good, no bugs noticeable.

- **Testing**:
  - Manual testing still needed, but instructions were given.
  - Coverage still >90%.

- **Functionality**:
  - Home screen modified to look similar to the rest of the app.
  - Home button added to game.

- **Housekeeping**:
  - No junk files, no AI mentioned.

### Additional Comments:

**Review by thegreatzoidberg — APPROVED** [review]

**Pull request merged**
