### PR TITLE
Adding Backend testing to GitHub Actions.

### LINKED ISSUE #81: Backend needs Github Actions to run tests for it
## Describe the issue

The backend for our web app is currently not being tested using GitHub Actions. We will need to implement a change to our current workflow to fix this.

## To Reproduce

See current workflow and how it reviews only our frontend.

## Expected behavior

Backend should be tested.

### PR DESCRIPTION
**Pull request by FernFinder**
## Overview
This pull request updates our GitHub Actions workflow to include testing for the backend.

## Related Issue(s)
Closes #81.

## Changes
The workflow file is updated to include a backend section now. This required some changes to the existing test in order to close the server connection after the tests are run. This must be done to prevent Jest from hanging. Comments have been added to assist with readability of code.

### Changed
Workflow file and Users.test.js file.

## Instructions for Testing
See GitHub Actions.

## Checklist before Merging
- [x] I have performed a self-review of my own code.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary documentation (if appropriate).
- [x] I have ensured the changes adhere to the project's coding standards and guidelines.

### CODE REVIEW

**Comment by FernFinder** [comment]
It looks like there is a limitation with GitHub Actions. See this Article:
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

Here is a forum thread on the topic:
https://github.com/orgs/community/discussions/50161

The workflow does not have access to the main repo's secrets. This leads to a login error that fails the test. On my fork the tests are working just fine.
image

**Comment by FernFinder** [comment]
Just an idea I have. We could merge all fork pull requests to a branch, for example 'merging'. This could then trigger a pull_request_target job that would have access to secrets. Once that job is finished and succeeds it can be merged to main.

**Comment by thegreatzoidberg** [comment]
### Pull Request Review:

- **Readability**:
  - New code is readable, well spaced-out, added comments.

- **Code Quality**:
  - Nothing here looks bad to me.

- **Testing**:
  - Workflow failed in the _Backend Coverage Report_ step, but it looks like a small fix in another file.
  - [Link for future reference](https://github.com/UNLV-CS472-672/2024-S-GROUP7-LifeQuest/actions/runs/8700530742/job/23860874679?pr=99)
  - Already working on solution anyways from the pull request comments.  Seems to be a secrets problem.

- **Functionality**:
  - More testing coverage, specifically backend.

- **Housekeeping**:
  - Don't see no junk files, don't see no AI mentioned.

### Additional Comments:
  - Great work!  Gonna need to open up a new Issue for current bug once this gets pulled.

**Review by thegreatzoidberg — APPROVED** [review]

**Review by barkangel — APPROVED** [review]
### Pull Request Review:

- **Readability**:
  - Workflow code and user.tests.js are readable

- **Code Quality**:
  - Code is adjusting previously created files that is easy to understand and general purpose is good.

- **Testing**:
 - Workflow fail, however this is not being merged into main so it's OK and further note that it will be merged to a separate branch from main confirmed on Discord.

- **Functionality**:
  - Modifies functionality of workflow, looks good.

- **Housekeeping**:
  - No AI used/mentioned, looks good to me.

### Additional Comments:
  - Nice job, PR approved for merging into new branch.

**Pull request merged**
