### PR TITLE
Homepage added

### LINKED ISSUE #16: Missing Home Page
## Describe the issue

TODO: Create home page for JS file

## Expected behavior

Needs to have 
- Triangle
- Stats
- Buttons
- Info on stats

## Screenshots

Examples:
image

### PR DESCRIPTION
**Pull request by dusek2**
## Overview
Adding homepage and homepage triangle components

## Related Issue(s)
Closes #16 Missing Homepage

## Changes
Adding homepage js file, CSS file.
You can access homepage under /home

### Added
- app/src/components/LifeQuestFormTriangle.js
- app/src/components/LifeQuestFormTriangle.module.css
- app/src/pages/home/Home.js
- app/src/pages/home/Home.module.css

### Changed
- app/src/App.js

## Screenshots

image

## Instructions for Testing
- cd app
- npm install
- npm run start
- access under http://localhost:3000/home

## Checklist before Merging
- [ ] I have performed a self-review of my own code.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have ensured the changes adhere to the project's coding standards and guidelines.

## Additional Comments
- Some text style discrepancies
- Not sure if the stats inside triangle are the correct module type

### CODE REVIEW

**Review by DillonDavidson — APPROVED** [review]
very nice

**Review by FernFinder — APPROVED** [review]
Nice start for the homepage, we should discuss how we want to render this webapp on PC vs. Mobile in today's meeting.

**Review by thegreatzoidberg — APPROVED** [review]
Should probably drop the "nameStat" parts and just call them "name", but it looks great otherwise.

**Review by MoldyPotat — COMMENTED** [review]
Very well put together and really like how the homepage is coming together.

**Pull request merged**
