### PR TITLE
Adding more unit tests index.js, skeleton.js

### PR DESCRIPTION
**Pull request by dusek2**
## Overview
Increasing test coverage to reach our CI goal

## Related Issue(s)
Related to #24 

### Added
- app/src/tests/Skeleton.test.js
- app/src/tests/index.test.js

## Instructions for Testing
npm run coverage

## Checklist before Merging
- [x] I have performed a self-review of my own code.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary documentation (if appropriate).
- [x] I have ensured the changes adhere to the project's coding standards and guidelines.

### CODE REVIEW

**Comment by dusek2** [comment]
Passed CI tests

**Comment by dusek2** [comment]
image

**Review by barkangel — APPROVED** [review]
### Pull Request Review:

**Readability**:
- Index, Skeleton, and Back Button tests look great. Very easy to understand.

**Code Quality**:
- Tests utilize a similar structure, allowing for ease of understanding. 
- data-testid's useful and follow a similar implementation scheme that I and others have implemented in other tests such as quest page and quiz page. 

**Testing**:
- Test files included as main component of PR.

**Functionality**:
- Code passes CI Workflow actions

### Additional Comments:
- woo 69% lines tested! very good improvement from a week ago.

**Comment by thegreatzoidberg** [comment]
### Pull Request Review:

**Readability**:
- Code spaced out well and has comments.  I'd say add more comments but I don't know where I would put them.

**Code Quality**:
- Code doesn't look like it has any bugs in them.  

**Testing**:
- Two more test files, bumps us up to 69.41%.
- Rest of modified files pass Workflow.

**Functionality**:
- More test coverage plus small modifications to already existing files.

**Housekeeping**:
- No junk files, no AI mentioned.

### Additional Comments:
- Should probably cross off the 4 checklist items if you've already done them.

**Review by thegreatzoidberg — APPROVED** [review]

**Pull request merged**
