### PR TITLE
Added features to the Settings Page and a test file

### PR DESCRIPTION
**Pull request by DillonDavidson**
## Overview
Created some features for the Settings Page (changing text size across pages, dark mode, a logout button skeleton, a delete account button skeleton, and a retake quiz button skeleton). The skeleton buttons are currently placeholders and will be fililed out as the project develops. More features will be added as the project progresses. Also, I cleaned up the pages directory.

## Related Issue(s)
Made the Settings Page do stuff, but no posted Issue.

## Changes
Created global font sizes for titles, text, and buttons to be modified by the Text Size buttons on the Settings page. Also, a "darkMode" class has been added to the .css files in the pages directory to facilitate the dark mode theme. Cleaned up the pages directory with specific directories for each page, and modified includes to appropriately handle that. I also created a test file for the Settings Page.

### Added
- app/src/tests/SettingsPage.test.js
- app/src/contexts/FontSizeContext.js
- app/src/pages/settings/SettingsPage.js
- app/src/pages/settings/SettingsPage.module.css
- app/src/pages/skeleton/Skeleton.js
- app/src/pages/skeleton/Skeleton.module.css
- app/src/pages/quests/QuestsPage.js
- app/src/pages/login/Login.css
- app/src/pages/login/Login.js

### Changed
- app/src/App.js
- app/src/global.css
- app/src/pages/home/Home.module.css

### Removed
- app/src/pages/SettingsPage.js
- app/src/pages/SettingsPage.module.css
- app/src/pages/Skeleton.js
- app/src/pages/Skeleton.module.css
- app/src/pages/Login.css
- app/src/pages/Login.js

### Fixed
- N/A

## Screenshots
image

## Instructions for Testing
npm install test
npm test

## Checklist before Merging
- [x] I have performed a self-review of my own code.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary documentation (if appropriate).
- [x] I have ensured the changes adhere to the project's coding standards and guidelines.

## Additional Comments
I will make the Settings Page look not awful, along with flushing out the skeleton buttons once the pieces for the project needed to link it up to are there. Also, I will work on making increasing our testing coverage.

### CODE REVIEW

**Review by dusek2 — APPROVED** [review]
Pull Request Review:
Readability:

Code is readable and easy to understand
Code Quality:

Code quality looks good.

Testing:
More test coverage needed!
Functionality:

Clear functionality but needs to be verified with unit tests

Additional Comments:

Great contribution

**Comment by dusek2** [comment]
looks like theres a conflict with login page @FernFinder

**Comment by barkangel** [comment]
I recently updated QuestsPage.js and QuestsPage.module.css in a pull request today, so there is a merge conflict.

**Review by Alexmc567 — APPROVED** [review]
### Readability:
Code is clear and understandable.

### Code Quality:
Code accurately does what it is supposed to do. Lack of comments on some parts of the added code however.

### Testing:
Does not fully hit the 90%, but close enough for now. Getting features up is more important than the missing ~15% coverage. 

### Functionality:
Features appear to work as intended.
Merge conflicts are the only issue that need to be resolved.

**Pull request closed without merging**
