### PR TITLE
Additional login page test

### PR DESCRIPTION
**Pull request by FernFinder**
## Overview
Added additional tests to the login page. The last thing big test that needs to be added is the function test. This will need #81 to be resolved first.

## Changes
Test 'renders without crashing' is more thorough now. 

### Added
Test 'input field updates value with current input' added to test input fields and see if they are updating values appropriately.

### Changed
General comments added for clarity.

## Instructions for Testing
See GitHub Actions tab.

## Checklist before Merging
- [x] I have performed a self-review of my own code.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary documentation (if appropriate).
- [x] I have ensured the changes adhere to the project's coding standards and guidelines.

### Additional Comments
Assistance from ChatGPT 3.5 used. Appropriate annotations used.
Conversation here: https://chat.openai.com/share/025568dc-22e7-4567-8d68-6e1a6b5b9cf8.
Slight modifications for my user case and testing of both input fields.

### CODE REVIEW

**Review by vicliyj — COMMENTED** [review]
Seems like there is something failing in the workflow!

**Comment by FernFinder** [comment]
Sorry about that, I was testing something else but I forgot to use a new branch. I reverted the commits so now the tests will pass.

**Review by vicliyj — APPROVED** [review]
Pull Request Review:
- Readability: Easy to follow and understand!
- Quality: Looks good!
- Functionality: Added unit test for login page.
- Housekeeping: AI use noted down where it was used, comments in place for what code does.

Great work!

**Review by DillonDavidson — APPROVED** [review]
### Pull Request Review:
**Readability:** Code is easy to read and understand
**Quality:** Quality of pull request is good, nice job
**Functionality:** Included a test for the added changes
**Housekeeping:** Comments added designating where AI was used for code generation.

Good job Fernando!

**Pull request merged**
