### PR TITLE
Adding PR Review Template

### LINKED ISSUE #34: Pull request review template missing
## Describe the issue

PR Review template necessary to ensure consistent accountable development.

## Possible Solution

Add a PR review template to /docs

### PR DESCRIPTION
**Pull request by dusek2**
## Overview
Pull request review template to create a consistent accountability system.

## Related Issue(s)
Closes #34 

## Changes
PR Review added.

### Added
- docs/pr_review_template.md

## Screenshots
image

## Instructions for Testing
Copy the template before reviewing the code.

## Checklist before Merging
- [ ] I have performed a self-review of my own code.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have ensured the changes adhere to the project's coding standards and guidelines.

### CODE REVIEW

**Review by Ruben14789 — APPROVED** [review]
- **Readability**:
    - Read the PR description. Does it align with the proposed changes? 
    - Check if the code is clear and the logic is easy to follow.

Answer: Yes the changes are easy to follow 

- **Code Quality**:
    - Are there comments explaining complex sections of code?
    - Is the programming style consistent with the project's standards?

Answer: Yes it is easy to understand and follows the project standards

- **Testing**:
    - Is Test coverage still >90%
    - Did code pass Github Actions CI system's pass all tests?

Answer: It is a PR template no functions or checks put

- **Functionality**:
    - Are all changes backwards compatible?
    - Does the PR resolve an existing issue?

Answer: yes it resolves the issue to make PR more of a standard flow of process 

- **Housekeeping**:
    - Are all files committed free from unnecessary (e.g., logs, 
      temporary files)?
    - Has any assistance from Generative AI been linked to PR or commented 
      below?
Answer: Yes all files cleared and no AI assistance used

**Comment by FernFinder** [comment]
I like it but I think we should reduce the boiler plating a little. Maybe we could leave the original doc as is but suggest using a format like this? I think deleting the section notes makes the PR more compact and easier to read. Additional Comments can also be omitted unless there is a need to use it.
<hr/>

### Pull Request Review Checklist:

- **Readability**:
Lorem Ipsum.

- **Code Quality**:
Lorem Ipsum.

- **Testing**:
Lorem Ipsum.

- **Functionality**:
Lorem Ipsum.

- **Housekeeping**:
Lorem Ipsum.

### Additional Comments:
Lorem Ipsum. Omit if no comments.

**Comment by thegreatzoidberg** [comment]
- **Readability**:
    - Read the PR description. Does it align with the proposed changes? 
    - Check if the code is clear and the logic is easy to follow.

Answer: Yes, the text is clear to follow.

- **Code Quality**:
    - Are there comments explaining complex sections of code?
    - Is the programming style consistent with the project's standards?

Answer: Yes, content is a text file, technically the whole thing is comments.  No programming style needed for text file.

- **Testing**:
    - Is Test coverage still >90%
    - Did code pass Github Actions CI system's pass all tests?

Answer:  Yes.  Not a program file, it is a text file.  Test coverage took no hit.

- **Functionality**:
    - Are all changes backwards compatible?
    - Does the PR resolve an existing issue?

Answer: Resolves Issue #34.  May need to update previous commit comments later.

- **Housekeeping**:
    - Are all files committed free from unnecessary (e.g., logs, 
      temporary files)?
    - Has any assistance from Generative AI been linked to PR or commented 
      below?
Answer: No unnecessary files included (just the main file).  No AI mentioned.

**Review by thegreatzoidberg — APPROVED** [review]

**Comment by thegreatzoidberg** [comment]
Probably wait for more people to review this.

**Comment by dusek2** [comment]
@FernFinder sure i agree lets make it more consise

**Review by barkangel — COMMENTED** [review]
Review Checklist:
- Readability:
  - The review template is easy to use and the 5 sections are helpful to improve code review. 

- Code Quality:
  - The code is easily understandable markup language.

- Testing:
  - No testing required as this is a PR template in docs directory.

- Functionality:
  - Very functional. This document will help us create PR's more easily and update the main branch more efficiently.

- Housekeeping:
  - The file is correctly in docs directory.

- Additional Comments:
  - Shortform review is good and allows for easier and faster PR return rate.

**Pull request merged**
