### PR TITLE
Added a registration page

### LINKED ISSUE #29: No Registration Page for Creating Account (Login Page)
## Describe the issue

Need an Account Registration page for new users.  Should be accessed from the Login page under the username and password boxes.

## Screenshots

Example

### PR DESCRIPTION
**Pull request by DillonDavidson**
## Overview
Created a Registration Page for users to create an account. Also included a test file for it.

## Related Issue(s)
closes #29 

## Changes
Created a new folder in pages called "registration" for the Registration Page. Created another test file to test the Registration Page. Updated app.js to have the registration page.

### Added
- app/src/pages/registration/RegistrationPage.js
- app/src/pages/registration/RegistrationPage.module.css
- app/src/tests/RegistrationPage.test.js

### Changed
- app/src/App.js

### Removed
- N/A

### Fixed
- N/A

## Screenshots
image

image

## Instructions for Testing
- npm start
- go to localhost3000/register

## Checklist before Merging
- [x] I have performed a self-review of my own code.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary documentation (if appropriate).
- [x] I have ensured the changes adhere to the project's coding standards and guidelines.

## Additional Comments
Registration Page has to be linked up to the backend still to save the new account and to be used to login. I'll try to get that up and running this weekend. Layout of the Registration Page heavily inspired/copied from the Login Page.

Test file generated with the use of ChatGPT
https://chat.openai.com/share/8500a5b2-a5fd-4bc2-8b69-5823401f8b7c

### CODE REVIEW

**Review by MoldyPotat — APPROVED** [review]
Pull Request Review:

Readability:

    Code is readable and easy to understand for the most part but I feels more comments could be added for documentation and readability to registrationPage.js.

Code Quality:
Code is of good quality as stated before could benefit from more comments but otherwise very good.

Testing:

    Tests pass, Good work keeping test coverage high.

Housekeeping:

    Code is clean and don't see any bloat good work.

Additional Comments:

    Very good work I do ask you add the ChatGPT usage to the pull request desc.
// Generated using ChatGPT
// https://chat.openai.com/share/8500a5b2-a5fd-4bc2-8b69-5823401f8b7c

**Review by FernFinder — CHANGES_REQUESTED** [review]
### Pull Request Review:

- **Readability**: Code is readable and is easy to understand. 

- **Code Quality**: Additional comments would be helpful but code is of a high quality.
- **Testing**: Great job including tests to help keep our coverage up. 

- **Functionality**: Code is functional and testing is passing. 

- **Housekeeping**: ChatGPT usage documented in app/src/pages/registration/RegistrationPage.js but please update it to use the format specified on this website. https://johnxu21.github.io/teaching/CS472/project/?

### Additional Comments:
Great job! Just add that AI documentation and this will be good to merge.

**Comment by DillonDavidson** [comment]
Updated documentation to match requirements

**Review by FernFinder — APPROVED** [review]
AI documentation updated. Approved.  👍

**Pull request merged**
