### PR TITLE
Added a skeleton for the settings page

### PR DESCRIPTION
**Pull request by DillonDavidson**
## Overview
Added a skeleton for the settings page. More features will come soon here.

## Changes
Adding SettingsPage.js and SettingsPage.module.css

### Added
- app/src/pages/SettingsPage.js
- app/src/pages/SettingsPage.module.css

### Changed
- app/src/App.js

## Screenshots
image

## Instructions for Testing
- cd app
- npm install
- npm start
- http://localhost:3000/settings 

## Checklist before Merging
- [ ] I have performed a self-review of my own code.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have ensured the changes adhere to the project's coding standards and guidelines.

## Additional Comments
Just a base skeleton for the settings page. More settings will be added and UI will be updated, this is just a starting off point to add on.

### CODE REVIEW

**Review by barkangel — COMMENTED** [review]
Good start for settings page. 
There seems to be a conflict with the most recent pull request involving App.js.
Wikipedia inclusion be changed to a different link in the future I presume.

**Comment by FernFinder** [comment]
Resolved merge error, just needed to fix the page routing.

**Review by barkangel — APPROVED** [review]
Looks like the merge conflict was resolved with App.js, nice swift work!
Merge approved.

**Review by thegreatzoidberg — COMMENTED** [review]
I don't see anything wrong with it.  It is a skeleton so if there is a bug, we can fix it later.

**Pull request merged**
