### PR TITLE
Adding API calls for Home Page Personal Statistics

### LINKED ISSUE #102: Getting user stats on HomePage
## Describe the issue

Homepage should show 3 user stats in percentage format.

## To Reproduce

Go to Homepage
check triangle stats

## Expected behavior

When user opens homepage his 3 main app stats should show
- MeStat
- LoveStat
- WorkStat

## Screenshots

current homepage
image

## Possible Solution

Add API calls to retrieve stats from backend

### LINKED ISSUE #123: Registration page needs register functionality
## Describe the issue

The registration page currently does not create a new user when credentials are provided.

## To Reproduce

Start frontend and backend.
Navigate to /registration.
Try to create a user.

## Expected behavior

A new user is created if a user does not exist already.

## Possible Solution

Update page to utilize users API. Update the users API to check for duplicate users.

### PR DESCRIPTION
**Pull request by dusek2**
## Overview
This pull request integrates new API calls for the Home Page Personal Statistics in the project. The purpose is to enhance user interaction by dynamically displaying personal statistics, thus making the application more responsive and personalized.

## Related Issue(s)
closes #102 

## Changes
The pull request includes modifications to the frontend and backend components to handle the fetching and display of personal statistics effectively. Specific updates were made to React components, CSS files, and backend routes.

### Added
- Added new API endpoint in `backend/routes/users.js` to handle fetching user statistics.
- Implemented error handling for unauthorized access in `app/src/components/LifeQuestFormTriangle.js`.

### Changed
- Updated the `.gitignore` files to ensure proper file exclusions.
- Modified the React component `LifeQuestFormTriangle.js` to include API call for fetching user stats and displaying them.
- Adjusted CSS in `LifeQuestFormTriangle.module.css` for better alignment and responsiveness.
- Refactored tests in `LifeQuestFormTriangle.test.js` to accommodate changes and ensure component functionality with mocked API responses.
- Changed Back Button design

### Removed
- Removed unnecessary lines and imports in various files that were redundant after refactoring.

### Fixed
- Fixed CSS positioning issues that affected the layout of elements on the Home page.

## Screenshots
image

## Instructions for Testing
1. Ensure the backend server is running and accessible.
2. Navigate to the home page after logging in. ( You have to log in to get login cookie, otherwise you will get booted to login page)
3. Check that the personal statistics are displayed correctly and update dynamically based on the logged-in user's data.
4. Attempt to access the page without authentication to verify that the user is redirected to the login page.
5. Run the unit tests in `app/src/tests` to ensure all components behave as expected after changes.

## Checklist before Merging
- [ ] I have performed a self-review of my own code.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have ensured the changes adhere to the project's coding standards and guidelines.

## Notes:

Later improvements:

Added Unit Tests 
Added comments to code
Changed Back Button design

### CODE REVIEW

**Review by FernFinder — APPROVED** [review]
### Pull Request Review:
- **Readability**:
PR description matches what was added and documents changes to code base well. The code itself is easy to follow and does not introduce bloat.

- **Code Quality**:
The code is functional and being tested. Proper indentation has been used along with comments to sections of code.

- **Testing**:
Testing coverage has been updated for this addition. Tests are passing.

- **Housekeeping**:
Some additional comments could be helpful for any team members not involved on the frontend of the project. No AI use so no documentation needed.

### Additional Comments:
Good job! The home page looks nice.

**Comment by dusek2** [comment]
In next PR i will implement api for grabbing currently logged users stats rather than just test email

**Review by barkangel — APPROVED** [review]
### Pull Request Review:
**Readability**:
- Code is readable and easy to understand where removals and additions are
- Not many comments with tue useEffect() feature, but that is alright. I'm planning on trying to do something similar with the quests page backend linkage.

**Code Quality**:
- Backend linkage added to multiple files including import axios from 'axios';
- app/src/components/LifeQuestFormTriangle.js provides good example of how to implement backend links

**Testing**:
- Tests pass, additions in app/src/tests/LifeQuestFormTriangle.test.js.
- Nice work.

**Housekeeping**:
- Inclusion of package-lock.json in gitignore is appreciated, I was unsure if that file was necessary or not whenever I was working on the frontend. 

### Additional Comments:
- Very good instructions on how to test the device
- The app is looking better and better everyday, nice work!
- Good to merge!

**Comment by dusek2** [comment]
Thanks for feedback i will add comments right now

**Pull request merged**
