### PR TITLE
Added base functionality to Quests page

### PR DESCRIPTION
**Pull request by barkangel**
## Overview
I added a few new features to the Quests page. This includes a section to view inprogress quests, a section to view available quests, a button to add an available quest to the inprogress quests section, and empty quest detection.

## Related Issue(s)
This PR closes issue #37  

## Changes
- Changed QuestsPage.js to add new functions and is now interactable
- Changed QuestsPage.module.css to add respective styles for QuestPage.js 

### Added & Changed
- Moved QuestsPage.js and QuestsPage.module.css to quests folder in pages directory
- Modified QuestsPage.js to include:
	- Updated navigation in imports
	- Added useState for quest title & text
	- Added addQuest function to set quests title and text
	- Added handleTitleChange function to modify quest title
	- Added handleTextChange function to modify quest text
	- Added addQuestToInProgress function which adds new quest to InProgress section
	- Added inProgress & available quest sections with maps to add quest and get their index, and determine if there are no in progress quests or available quests
- Modified QuestsPage.module.css to include corresponding styles for all additions made in QuestPage.js

## Screenshots
Current view of Quest page. Clicking add quest button will add the quest to the In progress section, and remove the text saying no quests in progress, aswell it will add text that says "No available quests" to the available quests section.
Screenshot Quests Page

## Checklist before Merging
- [x] I have performed a self-review of my own code.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary documentation (if appropriate).
- [x] I have ensured the changes adhere to the project's coding standards and guidelines.

## Additional Comments
- This PR just adds base functionality, more can be added on
- Will add functionality to pull from a file of sample quests titles and text 
- Will add functionality to mark quests complete and add them to a "completed quests" section
- Tests will be added in future pull request
- ChatGPT was used to assist with code documentation. 
  - Chat link: https://chat.openai.com/share/7e24fe17-a685-4b21-9d58-9eaafad8040a

### CODE REVIEW

**Comment by barkangel** [comment]
Need to commit again to fix quest files missing

**Comment by barkangel** [comment]
Files readded. PR is ready for review.

**Comment by thegreatzoidberg** [comment]
### Pull Request Review Checklist:

- **Readability**:
The code is commented so it's easy to follow.

- **Code Quality**:
I don't see any possible bugs from these two files, but fresh eyes are recommended.

- **Testing**:
Doesn't look like any new test files were added or whether the test files we already have cover this.

- **Functionality**:
Good and vital function to add.  What good is a quest page without quests to fill it?

- **Housekeeping**:
No extra log or temp files were added.  ChatGPT was used and noted by Brandon C., but barely and only for documentation.

### Additional Comments:
Nice work closing Issue #37, we're gonna need this.

**Review by thegreatzoidberg — APPROVED** [review]

**Review by MoldyPotat — APPROVED** [review]
Pull Request Review:

    Readability: Code Function and variable names make sense and easy to follow.

    Code Quality: Code looks like it was kept clean and simple don't see any issues with quality.

    Testing: Testing will need to be added as I don't see any test that cover the additions

    Functionality: Adds quest to quest page as needed.

    Housekeeping: No unnecessary files added and ChatGPT use was noted.

Additional Comments

**Pull request merged**
