### PR TITLE
Adjusting Home and App.js unit tests, increasing coverage 49% -> 59%

### PR DESCRIPTION
**Pull request by dusek2**
## Overview
Increasing test coverage and removing skeleton form routing.

## Changes
- Fixed issues with Github Actions for Home and App.js tests

### Changed
- app/src/App.js
- app/src/components/TopPanel.js
- app/src/tests/AppJs.test.js
- app/src/tests/AppJs.test.js

## Screenshots
image

## Instructions for Testing
npm run test
npm run coverage

## Checklist before Merging
- [ ] I have performed a self-review of my own code.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have ensured the changes adhere to the project's coding standards and guidelines.

### CODE REVIEW

**Comment by dusek2** [comment]
Chat GPT assistance 
https://chat.openai.com/share/9b2fd295-f6f7-472c-ad44-e366f9cba00f

**Comment by dusek2** [comment]
All checks have passed

**Review by MoldyPotat — APPROVED** [review]
Pull Request Review:

    Readability: 
Everything is well named and easy to follow.

    Code Quality:
Code is of good quality adding more testing in an understandable manner.

    Testing:
Increases testing closer to where it should be.

    Functionality:
Increases testing coverage and set some of the page links to navigate to correct page.

Additional Comments:
AI uses noted in pr.

**Comment by thegreatzoidberg** [comment]
### Pull Request Review:

- **Readability**:
  - Easy to read and has comments.

- **Code Quality**:
  - Code looks like it works.  Fixed some bugs with the original files.

- **Testing**:
  - More tests added and modified files pass all tests.
  - 
- **Functionality**:
  - More testing was added and App doesn't lead to skeleton anymore.

- **Housekeeping**:
  - No junk files, ChatGPT was used and conversation was linked.

### Additional Comments:

**Review by thegreatzoidberg — APPROVED** [review]

**Pull request merged**
