### PR TITLE
Login Page Styling Update

### LINKED ISSUE #83: Login page needs styling redesign
## Describe the issue

The login page does not currently reflect the design selected in the user study. 

## To Reproduce

Run application and navigate to http://localhost:3000/.

## Expected behavior

The login page should look similar to the screenshot.

## Screenshots

image

## Possible Solution

Redesign the login page's styling.

## Tags

#enhancement

### PR DESCRIPTION
**Pull request by FernFinder**
## Overview
The login page has now been updated to match the user study.

## Related Issue(s)
Closes #83.

## Changes
The login page now reflects what was selected for the user study. Comments have also been added to help make the code easier to read.

### Changed
All files in app/src/pages/login.

## Screenshots
image

## Instructions for Testing
Run application and navigate to http://localhost:3000/login.

## Checklist before Merging
- [x] I have performed a self-review of my own code.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary documentation (if appropriate).
- [x] I have ensured the changes adhere to the project's coding standards and guidelines.

## Additional Comments
No need for new tests, this is just a slight visual change.

### CODE REVIEW

**Comment by FernFinder** [comment]
It looks like my testing environment is giving me issues. I'll update this sometime later this week to be compatible with our tests. For now this will be a draft.

**Comment by FernFinder** [comment]
Testing issues fixed!

**Review by vicliyj — APPROVED** [review]
Pull Request Review:
Readability: Code is easy to read!
Code Quality: Quality is high, everything is easy to follow, read, and understand.
Testing: Looks like they're in there!
Functionality: Login page looked great! Great job matching it to the user study.
Housekeeping: Comments made it easier to read and follow.

**Review by DillonDavidson — APPROVED** [review]
### Pull Request Review:
**Readability:** Code is nice and easy to read
**Code Quality:** Code quality looks very good. Nice job!
**Testing:** Testing files are included.
**Functionality:** Login page looks good, our logo is clean!
**Housekeeping:** I always appreciate the comments, thank you!
Good job Fernando!

**Pull request merged**
