### PR TITLE
Database schemas added for user data, quests and settings

### PR DESCRIPTION
**Pull request by dusek2**
## Overview
Please provide a brief overview of what this pull request aims to achieve. For instance, you might be fixing a bug, adding a new feature, or updating documentation. 

## Related Issue(s)
Closes issue #73 Missing MongoDB schemas

## Changes
Users

### Users
- userID: ObjectId - Unique identifier managed by MongoDB
- username: String - Chosen username also an email.
- password: String - Hashed password ( we will figure out hashing later
- completed quiz: Boolean - Indicates if the user has completed placement quiz
- stats: Object - Main app stats
  - MeStat: Number
  - WorkStat: Number
  - LoveStat: Number
- quests: Array - List of quests the user has undertaken or completed.
- settings: Object - User's settings preferences like notifications, audio level, etc.

### Quests

- questID: ObjectId - Unique identifier managed by MongoDB
- title: String - Name of the quest.
- description: String - What the user needs to do.
- statImprovements: Object - Indicates which stats are improved upon completion.
  - MeStat: Number
  - WorkStat: Number
  - LoveStat: Number
- requirements: String - quest requirements

### Settings

- userId: links settings to user
- uiPreferences: stores users preferred UI settings
  - fontSize: number
  - theme: light/dark

### Added
- backend/models/settings.js
- backend/models/quests.js

### Changed
- backend/models/user.js
- app/.gitignore
- backend/.gitignore

## Checklist before Merging
- [x] I have performed a self-review of my own code.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary documentation (if appropriate).
- [x] I have ensured the changes adhere to the project's coding standards and guidelines.

## Additional Comments
Game data not included!

### CODE REVIEW

**Comment by dusek2** [comment]
ChatGPT4 assistance used to find out how to build schemas for Mongo
https://chat.openai.com/c/48c5ea05-d43b-421c-8d79-d9a686543155

**Review by MoldyPotat — APPROVED** [review]
### Pull Request Review:

- **Readability**: Each part of the schema is well defined and commented with easy to understand names.

- **Code Quality**: Code is of high quality and easy to read.

- **Testing**: Unsure if the code can even be tested.

- **Functionality**: Added database information storage required for the application.

- **Housekeeping**: Everything looks clean and in order.

### Additional Comments: Cannot open chatGPT message log will need others conformation on that.

**Comment by dusek2** [comment]
> ### Pull Request Review:
> * **Readability**: Each part of the schema is well defined and commented with easy to understand names.
> * **Code Quality**: Code is of high quality and easy to read.
> * **Testing**: Unsure if the code can even be tested.
> * **Functionality**: Added database information storage required for the application.
> * **Housekeeping**: Everything looks clean and in order.
> 
> ### Additional Comments: Cannot open chatGPT message log will need others conformation on that.

linked fixed, thank you

**Review by vicliyj — APPROVED** [review]
Pull Request Review:
Readability: Code is formatted well with the appropriate comments. Easy to read!
Code Quality: High quality code, everything is easy to follow.
Testing: Don't think tests are needed? Other input needed.
Functionality: Great functionality added!
Housekeeping: Comments in all appropriate and necessary places, easy to read, easy to follow workflow. Looks good to me!

Additional comments: ChatGPT link works!

**Pull request merged**
