### PR TITLE
Fixed dark mode and quiz page calculations

### PR DESCRIPTION
**Pull request by DillonDavidson**
## Overview
Fixed a bug on the quiz page were scores were not calculated correctly. Also added dark mode functionality to the remaining pages

## Related Issue(s)
No created issue, just some housekeeping.

## Changes
Updated the pages .JS and .CSS files to include dark mode and proper font scaling. Bug fixing in quiz page and some tidying up.

### Added
- N/A

### Changed
- app/src/pages/quiz/QuizPage.module.css
- app/src/pages/quiz/QuizPage.js
- app/src/pages/quests/QuestsPage.module.css
- app/src/pages/quests/QuestsPage.js
- app/src/pages/home/Home.module.css
- app/src/pages/home/Home.js

### Removed
- N/A

### Fixed
- Quiz page results always resulted in 0%. Now they are good.

## Screenshots
image

## Instructions for Testing
npm install
npm start
navigate to localhost:3000/quiz and fill out the quiz.

## Checklist before Merging
- [x] I have performed a self-review of my own code.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary documentation (if appropriate).
- [x] I have ensured the changes adhere to the project's coding standards and guidelines.

## Additional Comments
Mainly some small fixes, I'll work on unifying styles across pages next.

### CODE REVIEW

**Comment by dusek2** [comment]
### Pull Request Review:

- **Readability**:
- Code readable and easy to understand

- **Code Quality**:
- Quality looks good

- **Testing**:
- Passes CI checks

- **Functionality**:
- adds great functionality for users

**Review by dusek2 — APPROVED** [review]

**Review by Alexmc567 — APPROVED** [review]
### Readability:
Code is clear and understandable.

### Code Quality:
Code accurately does what it is supposed to do. 

### Testing:
Code does pass all tests.

### Functionality:
Correctly fixes all related bugs.

### Additional Comments:
Thanks for fixing the quiz score calculation bug :)

**Review by vicliyj — APPROVED** [review]
**PR Review:**

- Readability: Code is easy to read.
- Code Quality: Code is also easy to follow!
- Functionality: Really appreciate the dark mode! Functionality looks solid.

**Review by thegreatzoidberg — COMMENTED** [review]
### Pull Request Review:

- **Readability**:
  - I'd say it's readable, but more comments are always nice.

- **Code Quality**:
  - Code looks fine and doesn't look like it could cause issues.
- **Testing**:
  - Passed the workflow.  
  - No testing files were added. 

- **Functionality**:
  - Dark mode is always a welcome addition.
  
- **Housekeeping**:
  - No junk files, no AI mentioned. 
### Additional Comments:
  - I'll approve this last in case people still need more PR reviews.

**Review by barkangel — APPROVED** [review]
PR Review:

Readability: Easy to understand code.
Code Quality: Quality code, and incorporated well into features of pages 
Functionality: I was thinking of adding a dark mode too for quests page, so this is great. Good work!

**Pull request merged**
