### PR TITLE
MongoDB database connection and first APIs for user data

### LINKED ISSUE #123: Registration page needs register functionality
## Describe the issue

The registration page currently does not create a new user when credentials are provided.

## To Reproduce

Start frontend and backend.
Navigate to /registration.
Try to create a user.

## Expected behavior

A new user is created if a user does not exist already.

## Possible Solution

Update page to utilize users API. Update the users API to check for duplicate users.

### PR DESCRIPTION
**Pull request by dusek2**
## Overview
Creating MongoDB connection and an API to add, retrieve and delete user from database

## Related Issue(s)
Closes #75 

## Changes
Created mongo connection in app.js of backend.
Created users.js routing for database APIs
Implemented usage of .env to hide database access URI
Changed login.js to remove database connection and move to app.js instead

### Added
- backend/.env
- backend/README.md
- backend/tests/users.test.js

### Changed
- backend/routes/users.js
- backend/routes/login.js

## Screenshots

Mongo DB record
image

Test coverage over 80%
image

## Instructions for Testing

After cloning repo
- add database URI string from MongoDB into .env file
- create API
- create API uni test
- npm test

## Checklist before Merging
- [x] I have performed a self-review of my own code.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary documentation (if appropriate).
- [x] I have ensured the changes adhere to the project's coding standards and guidelines.

### CODE REVIEW

**Comment by dusek2** [comment]
ChatGPT assistance used on Unit tests on user data API
https://chat.openai.com/share/351f7b76-3924-48ba-8891-4c8e4336d408

**Comment by dusek2** [comment]
Test coverage is over 80% but not yet implemented into Github Actions, I have to look into how to use APIs in Github Actions. It means we need the backend running and connected to database with secret URI and also the tests running simultaneously

**Review by FernFinder — APPROVED** [review]
### Pull Request Review:
Readability:
The code does as is stated in the PR. The current code implemented is logical and makes sense and is easy to follow.

Code Quality:
Comments are included and the code fits the current structure of our project.

Testing:
Test coverage is over 80% but is yet to implemented in GitHub actions. I have created issue #81 for this.

Functionality:
Changes are backward compatible and solve #75.

Housekeeping:
All AI use has been documented.

### Additional Comments:
Huge job on creating basic API requests for user schemas in our database. Good job also including testing and adding a .env file for our connection code. Approved.

**Review by barkangel — APPROVED** [review]
### Pull Request Review:
Readability:
Code is easy to follow and easy to read, files have respective changes listed in PR.

Code Quality:
Code is written well, no overflow, and documentation is present. 

Functionality:
Solves issue #75. and code is necessary for testing and backend connections.

Housekeeping:
Documentation is very good. ChatGPT4 is used, and documented where used. 

### Additional Comments:
Great work with testing percentage as well as backend connection. Great work, and a huge help bringing all aspects of the project together. A good transition into the backend stage of our webapp development.

Comments are very helpful and appreciated when connecting to backend.

PR approved and merging good to go!

**Pull request merged**
